version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    container_name: some-postgres-test
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/webapi-golang
    volumes:
      - webapi-golang:/var/lib/postgresql/data

volumes:
  webapi-golang: